### ISSUE TITLE
Just download Coco 2017?

### ISSUE THREAD

**Issue by longmalongma** [haochenheheda/Training-code-of-STM#1]
Hi, thanks for your good work. Just download Coco 2017?Does your training script replicate the results from the STM paper?
![image](https://user-images.githubusercontent.com/40291722/115500621-3e63db80-a2a4-11eb-9c4c-1515cc3ba806.png)

**Comment by haochenheheda** [comment]
Yes, just download coco2017, davis2017 and youtube 2019.
The performance and weights could be seen [here](https://github.com/haochenheheda/Training-Code-of-STM#performance-on-davis17weights)

**Comment by longmalongma** [comment]
> Yes, just download coco2017, davis2017 and youtube 2019.
> The performance and weights could be seen [here](https://github.com/haochenheheda/Training-Code-of-STM#performance-on-davis17weights)

Do I need to download all the files with data sets in 2017?

**Comment by haochenheheda** [comment]
Just 2017 Train images and 2017 Train/Val annotations

**Comment by longmalongma** [comment]
> Just 2017 Train images and 2017 Train/Val annotations

Ok,thanks!
