### ISSUE TITLE
Some question about youtubevos result.

### ISSUE THREAD

**Issue by zy5037** [haochenheheda/Training-code-of-STM#3]
Hello, Can you publish the results of your youtubevos ?
I used the 82.0 davis model  to measure 51.8 on youtube vos, Is this consistent with the result you measured?
Looking forward for your apply!

**Comment by haochenheheda** [comment]
The structure of Youtube-VOS is more complicated than DAVIS. The annotation masks may not appear on the same frame and the object indices may not be in order. So the inference script of Davis is not applicable to Youtube-VOS.  In addition, all_frames will help to get better performance.

**Comment by zy5037** [comment]
I changed it according to the format of the YTB datasets, which can deal with the new appear targets in YTB.
What does all_frames mean and have you tested the results of STM on youtubevos by yourself? And what's the result?
Thanks for your apply.
